'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMUI.GUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--chs : Chinese default text, you can refer to it for translation--&gt;
        '''&lt;!--width : width of the object--&gt;
        '''&lt;!--/crlf/ : Automatically replace with newline--&gt;
        '''&lt;data&gt;
        '''	&lt;MainWindow&gt;
        '''		&lt;TitlePanel.1 chs=&quot;起始页面&quot; width=&quot;120&quot;&gt;Start Page&lt;/TitlePanel.1&gt;
        '''		&lt;TitlePanel.2 chs=&quot;管理模组&quot; width=&quot;120&quot;&gt;Manage Mod&lt;/TitlePanel.2&gt;
        '''		&lt;TitlePanel.3 chs=&quot;配置队列&quot; width=&quot;120&quot;&gt;Deploy Queue&lt;/TitlePanel.3&gt;
        '''		&lt;TitlePanel.4 chs=&quot;内容中心&quot;&gt;Content/crlf/Center&lt;/TitlePanel.4&gt;
        '''		&lt;TitlePanel.5 chs=&quot;设置选项&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property fandom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fandom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Gitee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gitee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Github() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Github", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property HC_巧克力() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HC_巧克力", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO_HC_巧克力() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO_HC_巧克力", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO椰林飘香() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO椰林飘香", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO河豚() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO河豚", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO熔岩菇() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO熔岩菇", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO神盾药剂() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO神盾药剂", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO野山葵() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO野山葵", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO金色椰子() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO金色椰子", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO防风草() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO防风草", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ICO陈年蓝月亮葡萄酒() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICO陈年蓝月亮葡萄酒", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property kofi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kofi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ModDrop_White32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ModDrop_White32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property NEXUS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEXUS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Outlook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Outlook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Paypal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paypal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;data&gt;
        '''	&lt;StardewValleyGamePath&gt;&lt;/StardewValleyGamePath&gt;
        '''	&lt;ModRepositoryPath&gt;&lt;/ModRepositoryPath&gt;
        '''	&lt;StardewValleyGameBackUpPath&gt;&lt;/StardewValleyGameBackUpPath&gt;
        '''	&lt;CategoryExportDefaultPath&gt;&lt;/CategoryExportDefaultPath&gt;
        '''	&lt;ModItemExportDefaultPath&gt;&lt;/ModItemExportDefaultPath&gt;
        '''	&lt;SubLibraryExportDefaultPath&gt;&lt;/SubLibraryExportDefaultPath&gt;
        '''	&lt;VisualStudioCodePath&gt;&lt;/VisualStudioCodePath&gt;
        '''	&lt;VisualStudioPath&gt;&lt;/VisualStudioPath&gt;
        '''	&lt;NotepadPath&gt;&lt;/NotepadPath&gt;
        '''
        '''	&lt;DownloadSmui [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property SettingsEmpty() As String
            Get
                Return ResourceManager.GetString("SettingsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property SMAPI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMAPI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Stardew_Valley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stardew_Valley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Steam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Steam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 农场布局规划器() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("农场布局规划器", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 呵呵鱼MOD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("呵呵鱼MOD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 哔哩哔哩() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("哔哩哔哩", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 存档进度检查器() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("存档进度检查器", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 存档预测器() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("存档预测器", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 椰林飘香() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("椰林飘香", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 模块() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("模块", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 橙() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("橙", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 河豚() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("河豚", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 熔岩菇() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("熔岩菇", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 爱发电() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("爱发电", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 白() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("白", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 神盾药剂() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("神盾药剂", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 紫() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("紫", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 红() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("红", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 绿() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("绿", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 蓝() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("蓝", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 野山葵() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("野山葵", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 金色椰子() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("金色椰子", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 防风草() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("防风草", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 陈年蓝月亮葡萄酒() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("陈年蓝月亮葡萄酒", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 青() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("青", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 黄() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("黄", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
